PhotoService/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('shops', views.shops_list, name='shops_list'),
    path('shops/<str:category>/', views.photos_category, name='photos_category'),
   # path('shops/<str:category>/', views.shops_detail, name='shops_detail'),
    path('posts', views.posts_list, name='posts_list'),
    path('mypage', views.mypage, name='mypage'),
    path('mypage/edit', views.mypage_edit, name='mypage_edit'),
    path('users/<int:pk>/', views.users_detail, name='users_detail'),
    path('photos/new/', views.photos_new, name='photos_new'),
    path('photos/<int:pk>/', views.photos_detail, name='photos_detail'),
    path('photos/<int:pk>/delete/', views.photos_delete, name='photos_delete'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    #path(r'^(?P<photo_id>[0-9]+)/like/$', views.like, name='like'),
]

app/templates/app/Hibari.html
<table>
    <tr>
        <th>店名：</th>
        <td>
            ラーメン二郎　{{ category.title }}
        </td>
    </tr>
    <tr>
        <th>住所：</th>
        <td>
            〒188-0001 東京都西東京市谷戸町3-27-24 ひばりヶ丘プラザ1F
        </td>
    </tr>
    <tr>
        <th>最寄り駅：</th>
        <td>
            西武池袋線『ひばりヶ丘駅』（268m）
        </td>
    </tr>
    <tr>
        <th>営業時間：</th>
        <td>
            	【月～金】11:30～14:30／17:45～21:15
【土】10:30～16:30
※麺が無くなりしだい終了。
        </td>
    </tr>
    <tr>
        <th>定休日：</th>
        <td>日曜（祝日不定休、営業有無は店内表示有）</td>
    </tr>
    <tr>
        <th>アクセス：</th>
        <td>南口からPARCO前の歩道を直進。そのまま道なりに進み十字路を越え、三叉路の角あたりに黄色い看板。徒歩3分程度。</td>
    </tr>
</table>

app/templates/app/Kabukicho.html
<table>
    <tr>
        <th>店名：</th>
        <td>
            ラーメン二郎　{{ category.title }}
        </td>
    </tr>
    <tr>
        <th>住所：</th>
        <td>
            〒160-0021 東京都新宿区歌舞伎町2-37-5 日新ビル1階
        </td>
    </tr>
    <tr>
        <th>最寄り駅：</th>
        <td>
            西武新宿線『西武新宿駅』（178m））
        </td>
    </tr>
    <tr>
        <th>営業時間：</th>
        <td>
            11:30～翌3:00
        </td>
    </tr>
    <tr>
        <th>定休日：</th>
        <td>水曜</td>
    </tr>
    <tr>
        <th>アクセス：</th>
        <td>駅側から歌舞伎町一番街を抜けた先にある交番の横。</td>
    </tr>
</table>

app/templates/app/Meguro.html
<table>
    <tr>
        <th>店名：</th>
        <td>
            ラーメン二郎　{{ category.title }}
        </td>
    </tr>
    <tr>
        <th>住所：</th>
        <td>
            〒153-0063 東京都目黒区目黒3-7-2
        </td>
    </tr>
    <tr>
        <th>最寄り駅：</th>
        <td>
            JR山手線、東急目黒線など『目黒駅』（766m））
        </td>
    </tr>
    <tr>
        <th>営業時間：</th>
        <td>
            12:00～15:00／18:00～23:00 ※日によって変更の場合あり
        </td>
    </tr>
    <tr>
        <th>定休日：</th>
        <td>水曜</td>
    </tr>
    <tr>
        <th>アクセス：</th>
        <td>西口を出て、正面の権之助坂を下る。下りきったら、右折（ローソンが目印）。しばらく進んだ道路の左手。徒歩15分くらい。</td>
    </tr>
</table>

app/templates/app/Mita.html
<table>
    <tr>
        <th>店名：</th>
        <td>
            ラーメン二郎　{{ category.title }}
        </td>
    </tr>
    <tr>
        <th>住所：</th>
        <td>
            〒108-0073 東京都港区三田2-16-4
        </td>
    </tr>
    <tr>
        <th>最寄り駅：</th>
        <td>
            JR山手線、JR京浜東北線『田町駅』（596m））
        </td>
    </tr>
    <tr>
        <th>営業時間：</th>
        <td>
            8:30～15:00／17:00～20:00 ※麺切れにて終了。
        </td>
    </tr>
    <tr>
        <th>定休日：</th>
        <td>日曜・祝日</td>
    </tr>
    <tr>
        <th>アクセス：</th>
        <td>国道1号桜田通り沿い。田町駅西口前より慶応仲通を道なりに直進。そのまま進んで三田二丁目の交差点を渡り、慶応大学正門の少し先。徒歩8分程度。</td>
    </tr>
</table>

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>詩物語</title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 
    <!-- Bootstrap Javascript(jQuery含む) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<body>
  {% include 'app/header.html' %}
        {% for message in messages %}
            <p class="message-success">{{ message }}</p>
        {% endfor %}
        
        {% block content %}
        {% endblock %}
        
<footer>
    <div class="container">
    </div>
</footer>

</body>

</html>

app/templates/app/index.html
{% extends 'app/base.html' %} {% block content %}

<div class="top-wrapper">
  <div class="container">
    <h1>あなただけの詩二郎を共有しよう。
        <div class="btn-wrapper">
          <a href="#" class="btn facebook"><span class="fa fa-facebook"></span>Facebookでシェア</a>
          <a href="#" class="btn twitter"><span class="fa fa-twitter"></span>Twitterでシェア</a>
        </div></h1>
  </div>
</div>

<div class="aboutsite-wrapper">
  <div class="heading">
    <h3>詩二郎(うたじろう)とは？</h3><br>
    <p>二郎〇〇店にまつわる詩を共有するSNSです。</p>
    <p></p>
    <p>・二郎〇〇店にまつわる思い出や思い入れ</p>
    <p>・二郎〇〇店にまつわる自作のポエム</p>
    <p>・二郎〇〇店の二郎にピッタリの歌詞</p>
    <p></p>
    <p>などなど、思い思いの詩二郎を自由に投稿してください。</p>
  </div>
</div>

{% include 'app/posts_list_new.html' %}

<div class="message-wrapper">
  <div class="container">
    <div class="heading">
      <h3>さぁ、あなたも詩二郎に投稿しましょう！</h3>
    </div>
    <span class="btn message">新規登録して投稿する</span>
  </div>
</div>

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}

<div class="top-wrapper">
<div class="login">
<form class="form-signin" method="post">{% csrf_token %}
    <h2>ユーザーログイン</h2><br>
    {% if form.errors %}
        <p>ユーザー名かパスワードが間違っています。もう一度入力してください。</p>
    {% endif %}
    <label>ユーザー名：</label>
    <input name="username">
    <br>
    <label>パスワード：</label>
    <input type="password" name="password">
    <br>
    <br>
    <div class="send">
    <input type="submit" value="ログイン">
    </div>
</form>
</div>
</div>

{% endblock %}

app/templates/app/password_change.html
{% extends "app/base.html" %}

{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

app/templates/app/password_change_done.html
{% extends "app/base.html" %}
{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'app:login' %}">ログイン</a>
</p>
{% endblock %}

app/templates/app/photos_detail.html
{% extends 'app/base.html' %}

{% block content %}

<div class="photo-detail">

{% if photo.image %}
<img src="{{ photo.image.url }}" class="photo-img">
{% else %}
<img src="https://kentohomma-first-bucket.s3-ap-northeast-1.amazonaws.com/ramen0I9A9583_TP_V.jpg" class="photo-img">
{% endif %}

<div class="photo-info">
    <a href="{% url 'app:users_detail' photo.user.id %}">@{{ photo.user }}</a>
</div>

<h2>{{ photo.title }}</h2>
<p>{{ photo.comment }}</p>


<!-- 削除ボタン -->
{% if request.user == photo.user %}
<form method="post" action="{% url 'app:photos_delete' photo.id %}">{% csrf_token %}
    <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
</form>
{% endif %}
</div>
{% endblock %}

app/templates/app/photos_new.html
{% extends 'app/base.html' %}

{% block content %}

 <div class="top-wrapper">
      <div class="container">
        
<div class="phots_new">
<form action="{% url 'app:photos_new' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <h2>新規投稿</h2>
            <br>
            
            <div class="form-category">
            <lavel>店舗名</lavel><br>
            {{ form.category }}
            </div>
            
            <div class="form-title">
            <lavel>タイトル</lavel><br>
            {{ form.title }}
            </div>
            
            <div class="form-story">
            <lavel>コメント</lavel><br>
            {{ form.comment }}
            </div>
            
            <div class="form-image">
            <lavel>画像(任意)</lavel><br>
            {{ form.image }}
            </div>
            <br>
            
            <div class="send">
            <button type="submit" class="btn">投稿</button>
            </div>
</form>
</div>

</div>
</div>

{% endblock %}

app/templates/app/posts_list.html
{% extends 'app/base.html' %} {% block content %}

<div class="top-wrapper">
  <div class="container">
    <h1></h1>
    <h1>投稿一覧
      <h1>
        <div class="btn-wrapper">
          <a href="#" class="btn facebook"><span class="fa fa-facebook"></span>Facebookでシェア</a>
          <a href="#" class="btn twitter"><span class="fa fa-twitter"></span>Twitterでシェア</a>
        </div>
  </div>
</div>

{% if category %}
<h2>カテゴリー：{{ category.title }} の検索結果</h2>
{% endif %}

{% include 'app/posts_list_basic.html' %}


{% endblock %}

app/templates/app/signup.html
{% extends 'app/base.html' %}

{% block content %}

<div class="top-wrapper">
<div class="signin">
<form method="post" action="{% url 'app:signup' %}">{% csrf_token %}
    <h2>ユーザー新規登録</h2><br>
    <label>ユーザー名：  　　</label>
    {{ form.username }}
    {{ form.username.errors }}
    <br>
    <label>パスワード：  　　</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
    <br>
    <label>パスワード(確認)：</label>
    {{ form.password2 }}
    {{ form.password2.errors }}
    <br>
    <br>
    <div class="send">
    <input type="submit" value="登録">
    </div>
</form>
</div>
</div>
{% endblock %}

app/templates/app/users_detail.html
{% extends 'app/base.html' %} {% block content %}

<div class="aboutsite-wrapper">
    <div class="heading">
        
        <h2>ユーザー情報</h2>

        <table>
            <tr>
                <th>ユーザー名：</th>
                <td>
                    <h3 class="user-name">@{{ user.username }}</h3>
                </td>
            </tr>
            <tr>
                <th>アイコン：</th>
                <td><img src="https://kentohomma-first-bucket.s3-ap-northeast-1.amazonaws.com/2.jpg" class="profile-img"></td><br>
            </tr>
            <tr>
                <th>自己紹介：</th>
                <td>ここに自己紹介をレンダリングする。あとで長い文章でも大丈夫かのテストもしなきゃね。</td>
            </tr>
        </table>


        {% if photos.count != 0 %}
        <h2>投稿：<strong>{{ photos.count }}</strong>件</h2>
        {% include 'app/posts_list_basic.html' %} {% else %} {% if user == request.user %}
        <p>@{{ user.username }}さんはまだ投稿していません。</p>
        <p>初めての投稿をしてみましょう！</p>
        {% else %}
        <p>@{{ user.username }}さんはまだ投稿していません。</p>
        {% endif %} {% endif %}

    </div>
        {% endblock %}